version: '3.8'
services:
  eureka:
    image: atom8426/ct-eureka:latest
    container_name: ct-eureka-app
    networks:
      - spring-cloud-network
    ports:
      - "19090:19090"
    environment:
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
  gateway:
    image: atom8426/ct-gateway-dev:latest
    container_name: ct-gateway-app
    networks:
      - spring-cloud-network
    ports:
      - "19091:19091"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      JWT_SECRET: ${JWT_SECRET}
  userservice:
    image: atom8426/ct-userservice-dev:latest
    container_name: ct-userservice-app
    networks:
      - spring-cloud-network
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILE: dev
      CT_DB_USER: ${CT_DB_USER}
      CT_DB_PASSWORD: ${CT_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      NAVER_ID: ${NAVER_ID}
      NAVER_SECRET: ${NAVER_SECRET}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      KAKAO_ID: ${KAKAO_ID}
      KAKAO_SECRET: ${KAKAO_SECRET}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
    restart: always
  adminservice:
    image: atom8426/ct-adminservice:latest
    container_name: ct-adminservice-app
    networks:
      - spring-cloud-network
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILE: prod
      CT_DB_USER: ${CT_DB_USER}
      CT_DB_PASSWORD: ${CT_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    restart: always

networks:
  spring-cloud-network:
    driver: bridge